languages:
   PHP: true
engines:
   phpmd:
      enabled: true
      checks:
         Controversial/CamelCaseClassName:
            enabled: false
         Controversial/CamelCaseParameterName:
            enabled: false
