languages:
   PHP: true
#engines:
#   phpmd:
#      enabled: true
#      checks:
#         Controversial/CamelCaseClassName:
#            enabled: false
#         Controversial/CamelCaseMethodName:
#            enabled: false
#         Controversial/CamelCaseParameterName:
#            enabled: false
#         Controversial/CamelCasePropertyName:
#            enabled: false
#         Controversial/CamelCaseVariableName:
#            enabled: false
