<?php
use PHPUnit\Framework\TestCase;

if( ! class_exists( 'PHPUnit_Framework_TestCase' ) ) {
	class PHPUnit_Framework_TestCase  extends TestCase {
		function expectException( $exception ) {
			if ( method_exists( $this, 'expectException' ) ) {
				return parent::expectException( $exception ); // TODO: Change the autogenerated stub
			}
			return $this->setExpectedException( $exception );
		}
	}
}